#!/bin/sh 

case $1 in
    "initial-setup")
        script=initial-setup.sh
        ;;
    "post-reboot-setup")
        script=post-reboot-setup.sh
        ;;
    *)
        echo "Expected either --initial-setup or --post-reboot-setup"
        exit 1
        ;;
esac

cat << 'EOF' | sh
    set -e
    cd $(mktemp -d)
    wget -qO- https://github.com/maxouverzou/alpine-conf/archive/refs/heads/master.tar.gz | tar --strip-components 1 -xzf-
    sh ./$script
EOF

